applicants/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = "applicants"

urlpatterns = [
    path('applicants/', login_required(views.ApplicantListView.as_view()),name='applicant_list'),
    path('applicants/new/', login_required(views.ApplicantCreateView.as_view()),name='applicant_new'),
    path('applicants/<str:pk>/', login_required(views.ApplicantDetailView.as_view()),name='applicant_detail'),
    path('applicants/update/<str:pk>/', login_required(views.ApplicantUpdateView.as_view()),name='applicant_update'),
    path('applicants/delete/<str:pk>/', login_required(views.ApplicantDeleteView.as_view()),name='applicant_delete'),

    path('applicants/', login_required(views.JobApplicationListView.as_view()),name='jobapplication_list'),
    path('applicants/new/', login_required(views.JobApplicationCreateView.as_view()),name='jobapplicion_new'),
    path('applicants/<str:pk>/', login_required(views.JobApplicationDetailView.as_view()),name='jobapplicantion_detail'),
    path('applicants/update/<str:pk>/', login_required(views.JobApplicationUpdateView.as_view()),name='jobapplicantion_update'),
    path('applicants/delete/<str:pk>/', login_required(views.JobApplicationDeleteView.as_view()),name='jobapplicantion_delete'),

    ]

core/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'core'

urlpatterns = [
    path("", login_required(views.Index.as_view()), name="index"),

    path('countries/', login_required(views.CountryListView.as_view()),name='country_list'),
    path('countries/new/', login_required(views.CountryCreateView.as_view()),name='country_new'),
    path('countries/<str:pk>/', login_required(views.CountryDetailView.as_view()),name='country_detail'),
    path('countries/update/<str:pk>/', login_required(views.CountryUpdateView.as_view()),name='country_update'),
    path('countries/delete/<str:pk>/', login_required(views.CountryDeleteView.as_view()),name='country_delete'),

    path('states/', login_required(views.StateListView.as_view()),name='state_list'),
    path('states/new/', login_required(views.StateCreateView.as_view()),name='state_new'),
    path('states/<str:pk>/', login_required(views.StateDetailView.as_view()),name='state_detail'),
    path('states/update/<str:pk>/', login_required(views.StateUpdateView.as_view()),name='state_update'),
    path('states/delete/<str:pk>/', login_required(views.StateDeleteView.as_view()),name='state_delete'),

    path('districts/', login_required(views.DistrictListView.as_view()),name='district_list'),
    path('districts/new/', login_required(views.DistrictCreateView.as_view()),name='district_new'),
    path('districts/<str:pk>/', login_required(views.DistrictDetailView.as_view()),name='district_detail'),
    path('districts/update/<str:pk>/', login_required(views.DistrictUpdateView.as_view()),name='district_update'),
    path('districts/delete/<str:pk>/', login_required(views.DistrictDeleteView.as_view()),name='district_delete'),

]

jobs/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = "jobs"

urlpatterns = [
    path('jobs/', login_required(views.JobListView.as_view()),name='job_list'),
    path('jobs/new/', login_required(views.JobCreateView.as_view()),name='job_new'),
    path('jobs/<str:pk>/', login_required(views.JobDetailView.as_view()),name='job_detail'),
    path('jobs/update/<str:pk>/', login_required(views.JobUpdateView.as_view()),name='job_update'),
    path('jobs/delete/<str:pk>/', login_required(views.JobDeleteView.as_view()),name='job_delete'),

    # path('countries/', login_required(views.CountryListView.as_view()),name='country_list'),
    # path('countries/new/', login_required(views.CountryCreateView.as_view()),name='country_new'),
    # path('countries/<str:pk>/', login_required(views.CountryDetailView.as_view()),name='country_detail'),
    # path('countries/update/<str:pk>/', login_required(views.CountryUpdateView.as_view()),name='country_update'),
    # path('countries/delete/<str:pk>/', login_required(views.CountryDeleteView.as_view()),name='country_delete'),
    #
    # path('states/', login_required(views.StateListView.as_view()),name='state_list'),
    # path('states/new/', login_required(views.StateCreateView.as_view()),name='state_new'),
    # path('states/<str:pk>/', login_required(views.StateDetailView.as_view()),name='state_detail'),
    # path('states/update/<str:pk>/', login_required(views.StateUpdateView.as_view()),name='state_update'),
    # path('states/delete/<str:pk>/', login_required(views.StateDeleteView.as_view()),name='state_delete'),

    path('skills/', login_required(views.SkillListView.as_view()),name='skill_list'),
    path('skills/new/', login_required(views.SkillCreateView.as_view()),name='skill_new'),
    path('skills/<str:pk>/', login_required(views.SkillDetailView.as_view()),name='skill_detail'),
    path('skills/update/<str:pk>/', login_required(views.SkillUpdateView.as_view()),name='skill_update'),
    path('skills/delete/<str:pk>/', login_required(views.SkillDeleteView.as_view()),name='skill_delete'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.documentation import include_docs_urls
from rest_framework.schemas import get_schema_view
from django.views.generic import TemplateView


schema_view = get_schema_view(title="Project API")


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include_docs_urls(title="Project API Documentation")),
        path('schema', schema_view),
        path('accounts/', include('registration.backends.simple.urls')),

        path("app/", include("core.urls", namespace="core")),
        path("users/", include("users.urls", namespace="users")),
        path("services/", include("services.urls", namespace="services")),
        path("jobs/", include("jobs.urls", namespace="jobs")),
        path("applicants/", include("applicants.urls", namespace="applicants")),
        path("recruiters/", include("recruiters.urls", namespace="recruiters")),


        path("api/v1/users/", include("api.v1.users.urls", namespace="api_v1_users")),
        path("api/v1/services/", include("api.v1.services.urls", namespace="api_v1_services")),

        path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
        path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
        path('tinymce/', include('tinymce.urls')),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "Project Administration"
admin.site.site_title = "Project Admin Portal"
admin.site.index_title = "Welcome to Project Admin Portal"

recruiters/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = "recruiters"

urlpatterns = [
    path('recruiters/', login_required(views.RecruiterListView.as_view()),name='recruiter_list'),
    path('recruiters/new/', login_required(views.RecruiterCreateView.as_view()),name='recruiter_new'),
    path('recruiters/<str:pk>/', login_required(views.RecruiterDetailView.as_view()),name='recruiter_detail'),
    path('recruiters/update/<str:pk>/', login_required(views.RecruiterUpdateView.as_view()),name='recruiter_update'),
    path('recruiters/delete/<str:pk>/', login_required(views.RecruiterDeleteView.as_view()),name='recruiter_delete'),

        ]

services/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path('services/', login_required(views.ServiceListView.as_view()),name='service_list'),
    path('services/new/', login_required(views.ServiceCreateView.as_view()),name='service_new'),
    path('services/<str:pk>/', login_required(views.ServiceDetailView.as_view()),name='service_detail'),
    path('services/update/<str:pk>/', login_required(views.ServiceUpdateView.as_view()),name='service_update'),
    path('services/delete/<str:pk>/', login_required(views.ServiceDeleteView.as_view()),name='service_delete'),

    path('categories/', login_required(views.CategoryListView.as_view()),name='category_list'),
    path('categorys/new/', login_required(views.CategoryCreateView.as_view()),name='category_new'),
    path('categorys/<str:pk>/', login_required(views.CategoryDetailView.as_view()),name='category_detail'),
    path('categorys/update/<str:pk>/', login_required(views.CategoryUpdateView.as_view()),name='category_update'),
    path('categorys/delete/<str:pk>/', login_required(views.CategoryDeleteView.as_view()),name='category_delete'),


]

templates/app/partials/_footer.html
<footer class="footer">
    <div class="container-fluid clearfix">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © Go Service</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Powered by <a href="https://www.prospello.tech/" target="_blank">Prospello Technologies </a></span>
    </div>
</footer>

templates/app/partials/_navbar.html
{% load static %}
<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo" href="{% url 'core:index' %}"><img src="{% static 'app/images/logo.svg' %}" alt="logo" /></a>
        <a class="navbar-brand brand-logo-mini" href="{% url 'core:index' %}"><img src="{% static 'app/images/logo-mini.svg' %}" alt="logo" /></a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-stretch">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
        </button>
        <div class="search-field d-none d-md-block">
            <form class="d-flex align-items-center h-100" action="#">
                <div class="input-group">
                  
                    <input type="text" class="form-control bg-transparent border-0" placeholder="Search projects">
                </div>
            </form>
        </div>
        <ul class="navbar-nav navbar-nav-right">

            <li class="nav-item d-none d-lg-block full-screen-link">
                <a class="nav-link">
                    <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
                </a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
                    <i class="mdi mdi-bell-outline"></i>
                    <span class="count-symbol bg-danger"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
                    <h6 class="p-3 mb-0">Notifications</h6>

                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-info">
                                <i class="mdi mdi-link-variant"></i>
                            </div>
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject font-weight-normal mb-1">Admin Launched</h6>
                            <p class="text-gray ellipsis mb-0"> New features out! </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <h6 class="p-3 mb-0 text-center">See all notifications</h6>
                </div>
            </li>

            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                    <div class="nav-profile-img">
                        <img src="{% static 'app/images/dashboard/face.jpg' %}" alt="image">
                        <span class="availability-status online"></span>
                    </div>
                    <div class="nav-profile-text">
                        <p class="mb-1 text-black">{{request.user}}</p>
                    </div>
                </a>
                <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                    <a class="dropdown-item" href="#">
                        <i class="mdi mdi-cached mr-2 text-success"></i> Activity Log </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'auth_logout' %}">
                        <i class="mdi mdi-logout mr-2 text-primary"></i> Signout </a>
                </div>
            </li>

        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
</nav>

templates/app/partials/_sidebar.html
{% load static %}
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
                <div class="nav-profile-image">
                    <img src="{% static 'app/images/dashboard/face.jpg' %}" alt="profile">
                    <span class="login-status online"></span>
                    <!--change to offline or busy as needed-->
                </div>
                <div class="nav-profile-text d-flex flex-column">
                    <span class="font-weight-bold mb-2">{{request.user}}</span>
                    <span class="text-secondary text-small">Project Manager</span>
                </div>
                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'core:index' %}">
                <span class="menu-title">Dashboard</span>
                <i class="mdi mdi-home menu-icon"></i>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-services" aria-expanded="false" aria-controls="ui-services">
                <span class="menu-title">Services</span>
                <i class="menu-arrow"></i>
                <i class="mdi mdi-crosshairs-gps menu-icon"></i>
            </a>
            <div class="collapse" id="ui-services">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a class="nav-link" href="{% url 'services:category_list' %}">Categories</a></li>
                    <li class="nav-item"> <a class="nav-link" href="{% url 'services:service_list' %}">Services</a></li>
                    <li class="nav-item"> <a class="nav-link" href="{% url 'jobs:job_list' %}">Jobs</a></li>
                    <li class="nav-item"> <a class="nav-link" href="{% url 'jobs:skill_list' %}">Skills</a></li>
                    <li class="nav-item"> <a class="nav-link" href="{% url 'applicants:applicant_list' %}">Applicants</a></li>
                    <li class="nav-item"> <a class="nav-link" href="{% url 'applicants:jobapplication_list' %}">JobApplication</a></li>
                    <li class="nav-item"> <a class="nav-link" href="{% url 'recruiters:recruiter_list' %}">Recruiters</a></li>

                </ul>
            </div>
        </li>


    </ul>
</nav>